### ISSUE TITLE
Exercise1 : User Class

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#1]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise1

Create a class User with name and age as its attribute. Instantiate two objects user1 and user2 with some value. Create a method compare that compares the age of user1 and user2. The method should be called in this way: user1.compare(user2) this method should return output like"john is older than mary" or "mary is older than john" based on their age comparision.

**Comment by osifoanosike** [comment]
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise1/User.js#L16: Use better naming convention.
- We don't have to call trim() serverally. This can be optimized.

**Comment by DOkwufulueze** [comment]
Corrections implemented.

**Comment by osifoanosike** [comment]
The Error handling part qualifies to be moved into a separate method.

**Comment by DOkwufulueze** [comment]
Code optimized.
