### ISSUE TITLE
Exercise10: Email and URL format verification

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#10]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise10

The form you create like https://www.dropbox.com/Add validations for the correct format of email and homepage(url) using regular expressions.Please use only Object oriented approach to write your code.

**Comment by osifoanosike** [comment]
Home page regex not working properly.

**Comment by DOkwufulueze** [comment]
Regex corrected.

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/javascript/blob/master/Exercise10/Validator.js#L29

This method can be split further. Discuss

**Comment by DOkwufulueze** [comment]
Method splitting done.
