### ISSUE TITLE
Exercise11: Matching numerical values and event propagation

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#11]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise11

Create a form with two textfields labeled "Enter Number" and "Result". When I enter something in first textfield and submit the form, it should write true in second textfield if entered value is numeric otherwise false. Also if entered value is not numeric, form should not be submitted.Please use only Object oriented approach to write your code.

**Comment by osifoanosike** [comment]
Not working as described in the question. You should change your  implementation.

**Comment by DOkwufulueze** [comment]
Implementation corrected.
