### ISSUE TITLE
Exercise12: Domain, sub-domain matching

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#12]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise12

Create a simple form with a textfield and a submit button. When I enter a URL in this textfield and submit the form, it should alert me the domain name from the entered url. For example, If I enter:1. http://example.com/, then on submitting the form it should alert something like: Domain: example.co m. 2.(with subdomain) http://vinsol., then on submitting the form it should alert something like:Domain: example.com, 

Subdomain: vinsol.Basic Idea is to extract domain name and subdomain from a URL.Note: Use Regular Expressions for thisexercise.Please use only Object oriented approach to write your code.

**Comment by osifoanosike** [comment]
- DomainShower: Use better naming convention.
- _init method used wrongly, its doing too much.
- Find a better way to match sections of your url. (Hint: Capture groups).

**Comment by DOkwufulueze** [comment]
Corrections implemented.

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/javascript/blob/master/Exercise12/DomainManager.js#L20

There's a better way to achieve this.
Look up Regular Expression Capture Groups

**Comment by DOkwufulueze** [comment]
Capture groups used.
