### ISSUE TITLE
Exercise2: Check all or none

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#2]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise2

Create a list of checkbox (red, green, yellow, white, black). Now create two links "Check all" and 'none'. When you click on check all link all checkbox will be selected, and when you click on none link all checkbox will be deselected(working example is gmail).

**Comment by osifoanosike** [comment]
- Naming convention: rename run to init.
- Unnecessary whitespaces

**Comment by DOkwufulueze** [comment]
Observed naming convention.
Unnecessary white spaces removed

**Comment by osifoanosike** [comment]
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise2/Check.js#L6
  Whitespace best practice not followed.

**Comment by DOkwufulueze** [comment]
White space best practice followed.
