### ISSUE TITLE
Exercise3: Maximum 3 Checkboxes selected

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#3]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise3

Create a list of checkboxs(Sunday, Monday, Wednesday, Thursday, Tuesday, Friday, Saturday and none). Now when I start checking these checkboxs, it should not let me check more than 3 checkboxes. When I try to check on 4th checkbox it should alert me as "Only 3 days can be selected. You have already selected sunday, monday and tuesday".Now when I click on none, all other checkboxs should be deselected. Also when 'none' is selected and I select any other option(lets assume sunday), that option(sunday) will be selected and none will be deselected.

**Comment by osifoanosike** [comment]
Do you need to redefine the 'days' in your js when you already have them in your html? Please optimize.

**Comment by osifoanosike** [comment]
Why do you have addCheckedButton() outside the class?

**Comment by DOkwufulueze** [comment]
The days array has been removed.

addCheckedButton() issue corrected.

Event Delegation implemented.
