### ISSUE TITLE
Exercise4: Parent checkbox, children checkboxes

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#4]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise4

Create a div with height 100 and scroll bars. Display a list of checkbox color, drinks, movies and bikes in this div. Now when you click on color checkbox it should display four checkboxes(red, yellow, green, blue) as a child list and color checkbox should be checked with its child list of checkboxes. Again when you click on color checkbox child list should be hidden and its child checkboxes should get deselected(clear state). Same with movies, drink and bikes.movies: [Dar, Sir]drinks: [coke, pepsi, dew]bikes: [V-rod, pulsar, cbz]Remember: When you click on a parent checkbox and if child list checkboxes are out of visible area the div's scrollbars should scroll and child list should be visible automatically. We should not scroll the div to see them(child list of checkboxes).

**Comment by osifoanosike** [comment]
- Use better naming conventions. We can discuss this.
- "...parentNode.parentNode.scrollTop": there is a better way

**Comment by osifoanosike** [comment]
- Re:better naming conventions
- Ensure all variable and method names are well descriptive. No abbreviations.
- Too many unnecessary whitespaces
- For event handling, the Airbnb Style guide suggests to use DOM level 2.   https://github.com/airbnb/javascript#events. You should use this.
- You don't need to hard-code the content of callerBox in your js, you should fetch them from the html
- Make use of event delegation. You don't need to iterate and attach event handlers to each child element.

**Comment by DOkwufulueze** [comment]
Corrections implemented.

Event Delegation implemented.

**Comment by osifoanosike** [comment]
ChildListShower: Use better naming convention.

You should have separate method to handle attaching event listeners. This shouldnt be done directly inside init.

**Comment by DOkwufulueze** [comment]
Better name used.
_init used minimally.
