### ISSUE TITLE
Exercise5: Dynamic table. Add new rows, edit and delete existing rows

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#5]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise5

Create a tableWhen you click on 'Add new row' button:
It should add a new row in the table.
In the name and email column there will a textfield.
In the action column there will be a button save.
When you enter some value in textfields and click save, then:
1. Values will be saved(if valid). i.e. Name should be present, Email should be a valid email.
2. Textfields will be replaced by the values entered.
3. Save button will be replace by edit / delete links.
   You should be able to delete row by clicking on the delete link, and edit value by clicking on the edit link.

**Comment by osifoanosike** [comment]
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise5/Row.js#L75
  This method is too long, and takes too many parameters..i.e its too generic. Method should be optimized and stream-lined as much as possible. To a max of 8-10 lines.
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise5/Row.js#L27
  This method can be further modularized. Its doing too much stuff.
- Too many DOM hits. You should pass  DOM elements u'll be re-using via ur class constructor, and set them as properties of the class, so you don't have to hit the DOM severally.
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise5/Row.js#L137
  When you need to start commenting out sections of a lengthy method, its a sign that the method is doing too much and needs to be further modularized. Please do so here.

**Comment by DOkwufulueze** [comment]
Lengthy parameters method gone.

Code Optimized and further modularized.

DOM hits correction implemented.

**Comment by osifoanosike** [comment]
You can find a better name for 'renderer'

init is performing more than its statutory role. Fix this.

The sections with descriptors/comments  in _addNewRow could as well be moved into separate units (methods) .

**Comment by DOkwufulueze** [comment]
Better name used, renderer removed.
_init used minimally.
Code optimized. Method parameters reduced.

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/javascript/blob/master/Exercise5/Table.js#L143
You can optimize the `if..else` further.
Comment and close the issue when this is done.

**Comment by DOkwufulueze** [comment]
Conditional statement optimized.
