### ISSUE TITLE
Exercuse6: Form validation using js

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#6]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise6

Create a form like https://www.dropbox.com/ and add JS validations to that form.When you click on 'Go' JS will check all text fields, and give an alert like "Login Id can't be 

empty". One alert per empty field.For textarea it should check for empty and min length of 50 characters.If any field is invalid then it should not submit the form. Also It should also confirm "receive notification"

**Comment by osifoanosike** [comment]
Code can be trimmed down.
e.g: _emptyMessage and _errorMessage can take a parameter and append 'Please enter ' to what it takes in. Each message don;t need to be this explicit

**Comment by DOkwufulueze** [comment]
Code trimmed down as advised.

**Comment by osifoanosike** [comment]
Home Page field validation not working properly.
init doing too much stuff. We should discuss this.

**Comment by DOkwufulueze** [comment]
Validation corrected.
_init used minimally.
