### ISSUE TITLE
Exercise7: Name input in alert and welcome in page content

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#7]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise7

Create a HTML page, when it opens in Browser, it should prompt twice. Once for first name and second for last name. When you enter first and last name, it should alert you as "Hello firstname lastname."After alert it should put that text in html page.Note: Keep in mind when you take inputs from users, always consider cases where user has entered null or blank values(few white spaces). User may pressed ESC button. In such cases you should not accept the input.

**Comment by osifoanosike** [comment]
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise7/Page.js#L15
  This method can be a one-liner.
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise7/Page.js#L26
  Nesting not optimal. There is a better way.

**Comment by DOkwufulueze** [comment]
Method turned to a one-liner.

Nesting optimized.

**Comment by osifoanosike** [comment]
Cool. However a better variable name can be used for element.

**Comment by DOkwufulueze** [comment]
Better Variable name used.

**Comment by osifoanosike** [comment]
https://github.com/OkwufuluezeD/javascript/blob/master/Exercise7/Page.js#L11

Init must be for initialization purposes only.

**Comment by DOkwufulueze** [comment]
_init used properly.
