### ISSUE TITLE
Exercise8: Input URL and open it

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#8]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise8

Write a Script that prompts you for a URL. If the input is an empty url it should alert you. Otherwise it should open that URL in a new window of width 400px and height 450px, without any type of bar(status bar, scroll bars etc..).

**Comment by osifoanosike** [comment]
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise8/URLOpener.js#L21
  Use better naming conventions
- https://github.com/OkwufuluezeD/javascript/blob/master/Exercise8/URLOpener.js#L26
  Method too long. It can be optmized.

**Comment by DOkwufulueze** [comment]
Naming convention observed.

Method optimized.

**Comment by osifoanosike** [comment]
Cool

**Comment by osifoanosike** [comment]
You can extract the content of init into a method and call it from init.

**Comment by DOkwufulueze** [comment]
_init minimized.
