### ISSUE TITLE
Exercise9: Move countries from one box to the other

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/javascript#9]
https://github.com/OkwufuluezeD/javascript/tree/master/Exercise9

Create two multiple selection boxFirst box contains list of countries and when you select a country and click on add button. Selected country will disappear from first box and appear in second button. And when you select a country from second box and click on remove button it will disappear from second box and appear in first box

**Comment by osifoanosike** [comment]
_init should be the entry point of your object. But right now, its doing stuff it shouldn't.

**Comment by DOkwufulueze** [comment]
_init used minimally.

**Comment by osifoanosike** [comment]
_sortBox method doing too much stuff.

The other comment out sections can be removed, leaving sortBox() to do the  actual sorting. The names for the new methods can be coined from the comments you gave. Discuss if unclear.

**Comment by DOkwufulueze** [comment]
_sortBox minimized.
